FROM python:3.12-slim

WORKDIR /app 

ENV PYTHONUNBUFFERED 1

COPY requirements.txt /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . /app

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]