version: '3.8'
services:
  django_p5:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    volumes:
      - .:/app
  postgres_db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    platform: linux/amd64

volumes:
  postgres_data: